### ISSUE TITLE
[PAL2] PAL 2 Todo list

### ISSUE THREAD

**Issue by NogginBops** [opentk/opentk#1686]
### Description
This is a TODO list for what remaining works needs to be done in PAL 2.

- [ ] Fix `IJoystickComponent` (figure out the API and if we should differentiate gamepads and joysticks)
- [ ] Investigate if `SetClipboardBitmap` is feasible (win32 implements this as a backend specific api).
- [ ] Formalize what format `IKeyboardComponent.GetActiveKeyboardLayout` returns.
- [ ] Add API for getting the current input langauge?
- [ ] Win32
  - [ ] Testing on different computers.
- [ ] X11
  - [ ] `X11DisplayComponent`:
    - [ ] Implement `GetDisplayScale()`.
    - [ ] Figure out if we can implement `WindowDpiChange` events.
  - [ ] `X11KeyboardComponent`:
    - [ ] Support XI2.
      - [ ] Implement IME API.
    - [ ] Figure out if we can get keyboard layout name and input language.
    - [ ] `KeySym` and scancode translation to OpenTK `Key` and `Scancode` types.
  - [ ] `X11MouseComponent`:
    - [ ] Implement `GetMouseState()`.
  - [ ] `X11ClipboardComponent`:
    - [ ] Implement `GetClipboardBitmap()` somehow (requires png decoding...)
  - [ ] `X11ShellComponent`:
    - [ ] More robust logic for `GetBatteryInfo`.
    - [ ] `GetPreferredTheme()`.
  - [ ] Events:
    - [ ] Implement `InputLanguageChanged`.
    - [ ] Implement `ClipboardUpdate`.
    - [ ] Implement `ThemeChange`.
    - [ ] Implement `WindowDpiChange`.
    - [ ] Implement `DisplayConnectionChanged`.
    - [ ] Implement `PowerStateChange`.
    - [ ] Implement `TextEditing`.
    - [ ] Implement `FileDrop`.
    - [ ] Implement `KeyDown`/`KeyUp`.
- [ ] macOS
  - [ ] `MacOSWindowComponent`:
    - [ ] `GetIcon()`/`SetIcon()`
    - [ ] `SetSize()`/`SetClientSize()`
    - [ ] `SetClientPosition()`
    - [ ] Min/Max window size
    - [ ] `GetDisplay()`
    - [ ] Fullscreen windows
    - [ ] Hit test callback
    - [ ] `SetCursor()`
    - [ ] Cursor capture modes
    - [ ] `ScreenToClient()`/`ClientToScreen()`
  - [ ] `MacOSMouseComponent`:
    - [ ] `SetPosition()`
  - [ ] `MacOSDisplayComponent`:
    - [ ] `GetWorkArea()`
    - [ ] `GetDisplayScale()`
    - [ ] Display connection/disconnection events.
  - [ ] `MacOSClipboardComponent`
  - [ ] `MacOSCursorComponent`
  - [ ] `MacOSIconComponent`
  - [ ] `MacOSKeyboardComponent`
  - [ ] `MacOSShellComponent`
- [ ] SDL
  - [ ] Figure out if we can do anything to figure out the keyboard layout name?
  - [ ] Figure out if we can do anything to get the preferred theme when using SDL2
  - [ ] Figure out how we should handle client vs non-client position and size.
  - [ ] Implement remaining events if possible.
- [ ] ANGLE
  - [ ] Make sure that `ANGLEOpenGLComponent` works with X11 and macOS backends.
