### ISSUE TITLE
PAL 2 MacOS TODO list

### ISSUE THREAD

**Issue by NogginBops** [opentk/opentk#1697]
### Description

A list of topics and issues to fix in the macOS backend.
See #1686 for all PAL 2 todos.

- [ ] Figure out what coordinate spaces we want to use for macOS.
- [ ] Figure out if we are leaking memory and if we can use autorelease pools (`@autoreleasepool` or `NSAutoreleasePool`).
- [ ] `MacOSWindowComponent`:
  - [x] `GetIcon()`/`SetIcon()` (atm these do nothing visible) + `SetDockIcon()` (as part of #1685)
  - [x] `SetSize()`/`SetClientSize()` (as part of #1685)
  - [ ] `SetClientPosition()`
  - [x] Min/Max window size (as part of #1685)
  - [x] `GetDisplay()` (as part of #1685)
  - [ ] Fullscreen windows
  - [ ] Hit test callback
  - [x] `SetCursor()` (as part of #1685)
  - [ ] Cursor capture modes
  - [ ] `ScreenToClient()`/`ClientToScreen()`
  - [ ] Make `WindowBorderStyle.ToolBox` work.
- [x] `MacOSMouseComponent`:
  - [x] `SetPosition()` (as part of #1685)
- [ ] `MacOSDisplayComponent`:
  - [x] `GetWorkArea()` (as part of #1685)
  - [x] `GetDisplayScale()` (as part of #1685)
  - [x] Get proper bits per pixel. (as part of #1685)
  - [x] Get proper refresh rate. (as part of #1685)
  - [ ] Display connection/disconnection events.
- [ ] `MacOSClipboardComponent`
- [ ] `MacOSCursorComponent`
  - [x] Load system cursors. (as part of #1685)
  - [x] Load "hidden" cursors for better matching cursors. (as part of #1685)
  - [x] Support animated cursors. (as part of #1685)
  - [x] `GetSize` for system cursors. (as part of #1685)
  - [x] `GetHotspot` for system cursors. (as part of #1685)
  - [x] `Create` with custom cursor images. (as part of #1685)
  - [x] Custom animated cursors. (as part of #1685)
  - [ ] Decide on the API for updating cursor animations (and if animations should have a on/off toggle).
  - [ ] Figure out if the current deprecated way of splitting the cursor frames is fine.
- [x] `MacOSIconComponent`
  - [x] Function for loading arbitrary SF Symbol icons. (as part of #1685)
- [ ] `MacOSKeyboardComponent`
- [ ] `MacOSShellComponent`
- [ ] Events:
  - [x] `Focus` (as part of #1685)
  - [x] `WindowMove`/`WindowResize` (as part of #1685)
  - [x] `WindowModeChange` (as part of #1685)
  - [ ] `WindowDpiChange`
  - [x] `MouseEnter` (as part of #1685)
  - [ ] `KeyDown`/`KeyUp`
  - [x] `TextInput` (as part of #1685)
  - [ ] `TextEditing`
  - [ ] `InputLanguageChanged`
  - [ ] `FileDrop`
  - [ ] `ClipboardUpdate`
  - [ ] `ThemeChange`
  - [ ] `DisplayConnectionChanged`
  - [ ] `PowerStateChange`
