### ISSUE TITLE
PAL 2 X11/Linux TODO list

### ISSUE THREAD

**Issue by NogginBops** [opentk/opentk#1698]
### Description

A list of topics and issues to fix in the X11/Linux backend.
See #1686 for all PAL 2 todos.

- [ ] `X11DisplayComponent`:
  - [ ] Implement `GetDisplayScale()`.
  - [ ] Figure out if we can implement `WindowDpiChange` events.
- [ ] `X11KeyboardComponent`:
  - [ ] Support XI2.
    - [ ] Implement IME API.
  - [ ] Figure out if we can get keyboard layout name and input language.
  - [ ] `KeySym` and scancode translation to OpenTK `Key` and `Scancode` types.
  - [ ] `GetKeyboardModifiers()`.
- [x] `X11MouseComponent`:
  - [x] Implement `GetMouseState()`. (as part of #1685)
- [ ] `X11ClipboardComponent`:
  - [ ] Implement `GetClipboardBitmap()` somehow (requires png decoding...)
- [ ] `X11ShellComponent`:
  - [ ] More robust logic for `GetBatteryInfo`.
  - [ ] Detect power saver mode.
  - [ ] `GetPreferredTheme()`.
- [ ] Events:
  - [ ] Implement `InputLanguageChanged`.
  - [x] Implement `ClipboardUpdate`. (as part of #1685)
  - [ ] Implement `ThemeChange`.
  - [ ] Implement `WindowDpiChange`.
  - [ ] Implement `DisplayConnectionChanged`.
  - [ ] Implement `PowerStateChange`.
  - [ ] Implement `TextEditing`.
  - [x] Implement `FileDrop`. (as part of #1685)
  - [ ] Implement `KeyDown`/`KeyUp`.
