### ISSUE TITLE
[4.0] Checklist and work tracker for OpenTK 4.0

### ISSUE THREAD

**Issue by Nihlus** [opentk/opentk#823]
This issue has been replaced by the [projects board](https://github.com/opentk/opentk/projects).

## Current state of 4.0

4.0 is currently:

- [x] Building
- [ ] Testable
- [ ] Usable
- [ ] Released

### How to help: 

We need help moving subsystems over.

pick something from `milestone 3`, open a [WIP] PR and tag one of the maintainers.
We'll link the subsystem here to your pull request.

## Overall goals of 4.0

- Target .netstandard 2.0
- Change root namespace
- Split the library
- Adopt ADL and move everything but graphics to ADL.

[The wiki documents these goals in greater detail.](https://github.com/opentk/opentk/wiki/Long-term-goals-for-OpenTK-(4.0-onwards))

### `Milestone 1`

Establishing the ground work for 4.0.

- [x] Decide an administrative structure for the continued work on 4.0.
- [x] Finalize the structure of this document.
- [x] Finalize the style guide.

### `Milestone 2`

Getting ready for migration.

- [x] Merge all outstanding PRs.
- [x] Move 4.0 to master.
- [x] Make master the default branch.
- [x] Change all namespaces to the new root.

### `Milestone 3`

Moving subsystems into the new project.

- Base:
    - [x] OpenTK.Core
    - [x] OpenTK.Math
    - ~~OpenTK.Input~~ Input is now included in Windowing (#866)
- [x] [OpenTK.Audio](https://github.com/opentk/opentk/pull/805)
  - [x] [OpenTK.OpenAL](https://github.com/opentk/opentk/pull/805)
- [x] [OpenTK.Windowing](https://github.com/opentk/opentk/pull/867)
  - [x] [OpenTK.Windowing.Desktop](https://github.com/opentk/opentk/pull/867)
- [x] [OpenTK.Graphics](https://github.com/opentk/opentk/pull/864)
  - [x] [OpenTK.OpenGL](https://github.com/opentk/opentk/pull/864)
  - [x] [OpenTK.OpenGL.Extensions.*](https://github.com/opentk/opentk/pull/864)
  - [x] [OpenTK.OpenGLES](https://github.com/opentk/opentk/pull/864)
  - ~~[OpenTK.OpenGLSC](https://github.com/opentk/opentk/pull/864)~~
- Internals
    - [x] OpenTK.Bind
    - [x] OpenTK.Rewrite
    - [x] OpenTK.Translate

### `Milestone 4`

Tooling and packaging.

- [x] Package all subsystems using NuGet.
- [ ] Add an OpenTK.Starter metapackage
- [x] Ensure a one-step build for the entire system and all packages.
- [ ] Setup a MyGet feed for the packages.
- [ ] Get all of the packages building via CI on MyGet.

### `Milestone 5`

Testing the upgrade and integration path. (4.0.0-pre)

- [ ] Try to migrate a few bigger projects to OpenTK 4.0.0-pre.
- [ ] Test and fix issues that may arise.

### `Milestone 6`

- [ ] Release 4.0.0

### `Future Goals`

- Add Support for OpenCL

**Comment by DylanFPS** [comment]
Wowza that's a read, but thanks! 👍

**Comment by DylanFPS** [comment]
Also, none of the anchor links work in the "Table of Contents"

**Comment by Nihlus** [comment]
@BMarques OpenTK isn't a games library as such, but rather a wider low-level library that can be used for a multitude of things.

OpenTK.Compute was never implemented, and at present we only really have some infrastructure in the binder to generate API bindings.

As for SDL, dropping it means dropping our implementation of it, and shifting it over to something like SDL.NET instead of having us maintain it. We can't drop the native platforms, because SDL is incapable of embedding itself as a widget in a UI toolkit.

Creating completely new subsystems without someone willing to maintain and champion it isn't in the scope of 4.0 at the moment.

**Comment by DylanFPS** [comment]
> Is OpenTK meant to be a games library

OpenTK is a toolkit of C# OpenGL, OpenCL, and OpenAL bindings. It was never meant to be a games library, bu... darn @Nihlus I was mid-way writing my comment!

> OpenTK also has too many platform subsystems

Not at all. Besides, if we were to drop some we'd be stripping functionality from the new release that'd been in previous releases - and we'd rather not do that. It's not like we have a big workload anyway as we have most of the bindings done already, we just need to refactor them to the new structure but we all are very busy and, as a result, can't work on this too much :|

> I'd like to suggest also to create a new subsystem that handles text/fonts

Hmmm I don't think this is something that OpenTK should handle. There are a number of pure C# font libraries out there anyway, adding a font subsystem would add workload and tbh I want 4.0 in your hands ASAP.

**Comment by BMarques** [comment]
Thanks for both comments :), I was wondering about that for some time, good to have it cleared out.

**Comment by DylanFPS** [comment]
No problem. Also @Nihlus I think in the "Planned Milestones" section there should be a milestone that involves a pre-release, right now it implys we're gonna release it as soon as we deem it ready and I think it's best if the public has access to 4.0 before it's full release - so they can try it out and hopefully run into some bugs we can squish.

**Comment by Nihlus** [comment]
@DylanFPS That'd be Milestone 2 - runnable and testable. I can clarify.

**Comment by jvbsl** [comment]
I'm currently refactoring the code to get it to compile with the StyleCop, without restructuring to the new structure. That should imho ease the rest of the refactoring process a lot.

**Comment by varon** [comment]
It would be a LOT easier to read this if we could move it to the projects page.

It would be great if @daerogami could apply those PM skills and get everything in this document listed up there.

**Comment by DylanFPS** [comment]
Could do it tonight if you need, I know my way around Trello and such so shouldn’t be a problem :)

**Comment by DylanFPS** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Green labels represent the milestone the task is a part of, as outlined in #823](https://trello.com/c/JUysolbj/2-green-labels-represent-the-milestone-the-task-is-a-part-of-as-outlined-in-823)

**Comment by DylanFPS** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Blue labels represent the current adopter of the task, or "Team/Internal" if this is a collaborative decision](https://trello.com/c/e8MID9dS/3-blue-labels-represent-the-current-adopter-of-the-task-or-team-internal-if-this-is-a-collaborative-decision)

**Comment by Pyrdacor** [comment]
Is milestone 3 still up to date?

**Comment by varon** [comment]
@Pyrdacor - Thanks for the spot. Updated!

**Comment by daerogami** [comment]
> We are currently working on Milestone (3/4).

I think this needs updated, too.

**Comment by varon** [comment]
@daerogami - Cheers. Did update that; milestone 3 is almost completed, but we're still sorting out the last bits and bobs of the project structure before we sign off on that!

**Comment by mikart143** [comment]
Are there available any  previews ? That project is amazing and I am looking to use in my app but cross-platfrom version would be blessing

**Comment by copygirl** [comment]
@mikart143 For the record, you can make a cross-platform game with previous versions of OpenTK as well. There's a little game called Vintage Story that targets .NET 4.5.2 and from my knowledge it runs with few problems on both Linux and Mac with Mono. I play it myself on Linux regularly.

**Comment by Pyrdacor** [comment]
How are things going? Looking forward to 4.0 release.

**Comment by chilipepperhott** [comment]
It looks like this document has not been updated in a while. All the milestone 3 mini-jobs are checked off, yet there does not seem to be any changes reflecting that anywhere else in the document. I am just so excited for the OpenTk 4 release!

**Comment by varon** [comment]
The issue has been replaced with the [Projects Board](https://github.com/opentk/opentk/projects)

**Comment by AraHaan** [comment]
Nice, what about projects targeting ``netcoreapp3.0;netcoreapp3.1;netcoreapp5.0`` (the 5.0 is in preview on .net core)

**Comment by NogginBops** [comment]
@AraHaan `netcoreapp3.0;netcoreapp3.1;netcoreapp5.0` all support .net standard 2.0 so that won't be a problem afaik.

Someone else will have to comment about `GLControl`...

**Comment by varon** [comment]
If you're writing winforms stuff you might as well just use the old package of OpenTk with GLControl support.

We have no major plans to bring it forward unless someone can write a port for us.

**Comment by Barsonax** [comment]
@varon 

Thats a bummer to hear. We are using it for the Duality game engine https://www.duality2d.net/. We would really like a .NET standard version of OpenTk with a working GLControl as that would enable us to start using .NET core.
